'use strict'
/**
 * Main Class
 */
class InstaPago {

	/**
	 * Transaction code messages
	 * @type {Array}
	 */
	const TRANSACTION_CODES: []

	TRANSACTION_CODES["00"] = "APROBADO"
	TRANSACTION_CODES["01"] = "LLAME AL EMISOR"
	TRANSACTION_CODES["02"] = "CEDULA INVALIDA"
	TRANSACTION_CODES["03"] = "COMERCIO INVALIDO"
	TRANSACTION_CODES["04"] = "RETENGA Y LLAME"
	TRANSACTION_CODES["05"] = "TRANS. RECHAZADA"
	TRANSACTION_CODES["06"] = "ERROR"
	TRANSACTION_CODES["07"] = "RETENGA Y LLAME"
	TRANSACTION_CODES["12"] = "TRANS. INVALIDA"
	TRANSACTION_CODES["13"] = "MONTO INVALIDO"
	TRANSACTION_CODES["14"] = "TARJETA INVALIDA"
	TRANSACTION_CODES["15"] = "EMISOR INVALIDO"
	TRANSACTION_CODES["19"] = "REINTENTE TRANS."
	TRANSACTION_CODES["21"] = "LLAME AL EMISOR"
	TRANSACTION_CODES["25"] = "REG. NO LOCALIZADO"
	TRANSACTION_CODES["28"] = "ARCHIVO. NO DISP."
	TRANSACTION_CODES["30"] = "ERROR EN FORMATO"
	TRANSACTION_CODES["39"] = "NO ES CTA. CREDITO"
	TRANSACTION_CODES["40"] = "FUNC. NO SOPORTADA"
	TRANSACTION_CODES["41"] = "TARJETA EXTRAVIADA"
	TRANSACTION_CODES["43"] = "TARJETA ROBADA"
	TRANSACTION_CODES["51"] = "FONDO INSUFICIENTE"
	TRANSACTION_CODES["52"] = "NO ES CTA. CTE."
	TRANSACTION_CODES["53"] = "NO ES CTA. AHORRO"
	TRANSACTION_CODES["54"] = "TARJETA VENCIDA"
	TRANSACTION_CODES["55"] = "CLAVE INVALIDA"
	TRANSACTION_CODES["57"] = "TRANS.NO PERMITIDA"
	TRANSACTION_CODES["58"] = "TRANS,NO PERMITIDA"
	TRANSACTION_CODES["61"] = "EXC.MONTO RETIROS"
	TRANSACTION_CODES["62"] = "TARJ. RESTRINGIDA"
	TRANSACTION_CODES["63"] = "FALLA SEGURIDAD"
	TRANSACTION_CODES["65"] = "EXCEDE RETIROS"
	TRANSACTION_CODES["68"] = "SIN RESP. DEL HOST"
	TRANSACTION_CODES["71"] = "EXCEPCION INVAL."
	TRANSACTION_CODES["72"] = "CONTRACARGO INVAL."
	TRANSACTION_CODES["75"] = "EXC. CLAVE INVAL."
	TRANSACTION_CODES["76"] = "CUENTA INVALIDA"
	TRANSACTION_CODES["77"] = "CUENTA INVALIDA"
	TRANSACTION_CODES["78"] = "CUENTA INVALIDA"
	TRANSACTION_CODES["79"] = "FECHA INVALIDA"
	TRANSACTION_CODES["80"] = "SIS. NO DISPONIBLE"
	TRANSACTION_CODES["81"] = "ERROR DE CLAVE"
	TRANSACTION_CODES["82"] = "TARJETA INVALIDA"
	TRANSACTION_CODES["83"] = "COD SEG INVALIDO"
	TRANSACTION_CODES["84"] = "AUTORIZ. INVALIDA"
	TRANSACTION_CODES["85"] = "NO RECHAZADA"
	TRANSACTION_CODES["86"] = "CLAVE NO VERIF."
	TRANSACTION_CODES["87"] = "CONCIL.DETENIDA"
	TRANSACTION_CODES["88"] = "TOTALES NO DISP."
	TRANSACTION_CODES["89"] = "INF. NO AUTORIZADA"
	TRANSACTION_CODES["90"] = "SERVICIO INACTIVO"
	TRANSACTION_CODES["91"] = "EMISOR INACTIVO"
	TRANSACTION_CODES["92"] = "SERVICIO NO DISP."
	TRANSACTION_CODES["93"] = "TRANS. INCOMPLETA"
	TRANSACTION_CODES["94"] = "TRANS. DUPLICADA"
	TRANSACTION_CODES["95"] = "ENVIANDO DETALLE"
	TRANSACTION_CODES["96"] = "SISTEMA INACTIVO"
	TRANSACTION_CODES["97"] = "SIN RESP. DEL HOST"
	TRANSACTION_CODES["99"] = "RECHAZADA"
	/**
	 * Response code descriptions
	 * @type {Array}
	 */
    const RESPONSE_CODES: []

	RESPONSE_CODES["201"] = "Pago procesado, se detalla la transacción en la respuesta."
	RESPONSE_CODES["400"] = "Error  al  validar  los  datos  enviados."
	RESPONSE_CODES["401"] = "Error de autenticación, ha ocurrido un error con las llaves utilizadas."
	RESPONSE_CODES["403"] = "Pago Rechazado por el banco."
	RESPONSE_CODES["500"] = "Ha Ocurrido un error interno dentro del servidor."
	RESPONSE_CODES["503"] = "Ha Ocurrido  un  error  al  procesar  los  parámetros  de  entrada.  Revise  los  datos 
enviados y vuelva a intentarlo."
	/**
	 * [description]
	 * @param  {[type]} apiKey    [description]
	 * @param  {[type]} publicKey [description]
	 * @return {[type]}           [description]
	 */

	_KeyId: ''
	_PublicKeyId: ''
	_Amount: ''
	_Description: ''
	_CardHolder: ''
	_CardHolderID: ''
	_CardNumber: ''
	_CVC: ''
	_ExpirationDate: ''
	_StatusId: ''
	_IP: ''
	_OrderNumber: ''
	_Address: ''
	_City: ''
	_ZipCode: ''
	_State: ''

	constructor: (apiKey, publicKey) => {
		this._KeyId = apiKey
		this._PublicKeyId = publicKey
	}

	createPayment: () => { }
}